Pull out a scaled slider class for finer grained control of slice positions
unibas-gravis/scalismo-ui pull request #51
Opened 2020-06-09 20:35 UTC by Andreas-Forster

This PR fixes #50 by introducing a new class [SubDividedSliderAdapter](https://github.com/Andreas-Forster/scalismo-ui/blob/098d92cfd6bf82fb3bdbe9c4ccc46412a0a6ecb0/src/main/scala/scalismo/ui/view/util/SubDividedSliderAdapter.scala#L22). The sliders have by default a 100x finer resolution than now. This should fix for most use cases the issue #50 where the slices could not be made visible by using the sliders.

2020-06-09 20:37 UTC, Andreas-Forster commented
Yet, this PR should serve as a discussion basis and testing is needed before merging it.

2020-06-10 14:13 UTC, clangguth requested changes
Looks good to me in general, I've added a few tiny nitpicking suggestions.

The only thing that still bothers me a bit is that most of the time references are made to the adapter, but sometimes to the contained slider. (listenTo(x.slider.slider)).

This could be overcome by making the adapter itself a ScalismoPublisher that listens to the slider events and re-publishes them on behalf of itself. Then the only occurence where direct access to the contained slider would still be needed is in the layout() calls, because they expect an actual Swing component.

2020-06-10 14:13 UTC, clangguth commented on src/main/scala/scalismo/ui/view/ViewportPanel.scala
> +  private val SubDivisions: Double = 100.0
This is obsolete and can be removed.

2020-06-10 14:13 UTC, clangguth commented on src/main/scala/scalismo/ui/view/ViewportPanel.scala
> +    override def apply(): Unit = positionSlider.up
```suggestion
    override def apply(): Unit = positionSlider.up()
```

2020-06-10 14:13 UTC, clangguth commented on src/main/scala/scalismo/ui/view/ViewportPanel.scala
> +    override def apply(): Unit = positionSlider.down
```suggestion
    override def apply(): Unit = positionSlider.down()
```

2020-06-10 14:13 UTC, clangguth commented on src/main/scala/scalismo/ui/view/properties/SlicingPositionPanel.scala
> +      override def apply(): Unit = slider.down
```suggestion
      override def apply(): Unit = slider.down()
```

2020-06-10 14:13 UTC, clangguth commented on src/main/scala/scalismo/ui/view/properties/SlicingPositionPanel.scala
> +      override def apply(): Unit = slider.up
```suggestion
      override def apply(): Unit = slider.up()
```

2020-06-10 14:13 UTC, clangguth commented on src/main/scala/scalismo/ui/view/util/SubDividedSliderAdapter.scala
> +  def slider: Slider = _slider
There is no need to introduce a private variable here, as it's an object anyway which is made accessible using this getter.

Therefore, my suggestion is to simply make `slider` a val. In the same vein, there's not really a need to keep `factor` private.

2020-06-10 20:25 UTC, Andreas-Forster commented on src/main/scala/scalismo/ui/view/ViewportPanel.scala
> +  private val SubDivisions: Double = 100.0
agree - addressed in new commit

2020-06-10 20:25 UTC, Andreas-Forster commented on src/main/scala/scalismo/ui/view/ViewportPanel.scala
> +    override def apply(): Unit = positionSlider.up
agree - addressed in new commit

2020-06-10 20:25 UTC, Andreas-Forster commented on src/main/scala/scalismo/ui/view/ViewportPanel.scala
> +    override def apply(): Unit = positionSlider.down
agree - addressed in new commit

2020-06-10 20:25 UTC, Andreas-Forster commented on src/main/scala/scalismo/ui/view/properties/SlicingPositionPanel.scala
> +      override def apply(): Unit = slider.down
agree - addressed in new commit

2020-06-10 20:25 UTC, Andreas-Forster commented on src/main/scala/scalismo/ui/view/properties/SlicingPositionPanel.scala
> +      override def apply(): Unit = slider.up
agree - addressed in new commit

2020-06-10 20:25 UTC, Andreas-Forster commented on src/main/scala/scalismo/ui/view/util/SubDividedSliderAdapter.scala
> +  def slider: Slider = _slider
agree - addressed in new commit

2020-06-10 20:33 UTC, Andreas-Forster commented
I made the SubDivdedSliderAdapter a ScalismoPublisher. Further, I had to introduce a new FancySliderDecorator as the FancySlider does not handle the position of the labels correctly.

It looks now that we have quite a few sliders classes. Not sure if there is a better solution.

2020-06-10 20:53 UTC, clangguth commented
Hmmm... ok, please give me a couple of days to take a closer look at how this can be properly solved.

2020-06-22 10:00 UTC, clangguth commented
Sorry, I don't currently find the time for a proper solution, but here's an idea/outline of a "one-size fits all" slider class which covers all existing use cases, maybe someone finds a way to implement it:
- ensure that it works with multiple types, not just integers. This would mean creating a new generic class which mimicks the interface of the existing Slider class, but in a typed way. Implementation-wise it could either wrap a JSlider or a Slider.
- include the formatting part of the FancySlider, so that labels can be shown if needed.
- the tricky part: ensure that it works for any domain (min/max) and that it allows to set a "step size" (or factor, or granularity, or whatever you want to call it).

Essentially, one needs to find functions to map from that "application domain" (AD) to a "slider domain" (SD) and back, where SD only consists of integers and the step size is always 1. However, min/max of SD could be adjusted if needed, but the largest possible range is (Int.MinValue, Int.MaxValue). The mapping between AD and SD would also need to be bijective, so that changes (movement of the slider) properly get propagated back to the application.

2020-06-23 11:44 UTC, Andreas-Forster commented
I added a quick draft for a `TypedSlider[A]` class which should work for `Int`, `Float` and `Double`. I replaced all sliders except the anonymous class using directly `scala.swing.Slider` [here](https://github.com/unibas-gravis/scalismo-ui/blob/020aae765941c77042a818f0d8a329df7132a13c/src/main/scala/scalismo/ui/view/properties/GaussianProcessCoefficientsPanel.scala#L59).

A quick test showed that it seems to work. However, I have not yet tested all classes I changed and maybe there is an unhandled corner case. For example, one could require that the step-size is always strictly positive. A lower bound for the step-size based on the min and max value could also make sense, in order to not prevent that the slider's internal value does not overflow. These should however not occur if you use the sliders in a reasonable range.

What do you think about the draft?

2022-03-20 14:26 UTC, marcelluethi commented
I lost track about the status of this PR. Is it okay to close it or are we close to something that can be merged?

2022-03-21 09:03 UTC, Andreas-Forster commented
I think we can close it for now. We could still pick it up later on.

2022-03-21 09:04 UTC, closed without merging